### ISSUE TITLE
Looking for a maintainer

### ISSUE THREAD

**Issue by yissachar** [yissachar/awesome-dart#104]
It's been a while since I've created this project and I no longer use Dart and am not in touch with the pulse of the community. As such, I've been unmotivated to keep up with the PRs that come in and find it hard to decide which projects to accept and which are not meeting the "awesome" criteria. I'm looking for someone to take over maintenance of this repo. Criteria is pretty simple - you should have good standing in the Dart community and have the time to review and merge/reject PRs. Please respond to this if interested, thanks :)

**Comment by Chinmay-KB** [comment]
I am probably not known in the community to command any standing, but I've been developing using dart for 3 years now. So can I  just sneak my name up here for being a maintainer 
* nervous *

**Comment by yissachar** [comment]
@Chinmay-KB Awesome, let's give it a shot - thanks :)

**Comment by tommydprogrammer** [comment]
Would love to be a contributor as well but not known in the community but i've been using dart for over 2.5 years now
