### ISSUE TITLE
Improve contribution guidelines

### ISSUE THREAD

**Issue by andresaraujo** [yissachar/awesome-dart#22]
I think it would be great to add the following to improve the quality of this list
- Sort items alphabetically
- Sort categories alphabetically
- Remove items that lack documentation
- Add link to the contributing guideline at the top of the README(before contents)
- Periodically check for unmaintained items and remove them
- Add pub link for items that are on pub, the format should be `[guthub](github-url)[pub](pub-url) - Description.`

**Comment by yissachar** [comment]
> - Sort items alphabetically
> - Sort categories alphabetically

I'm not sure if it's worth the effort to keep everything alphabetized. This is more of a discovery tool than an index, so I don't know that sorting alphabetically improves anything.

> - Remove items that lack documentation

Isn't this already covered by the current guidelines?

> - Add link to the contributing guideline at the top of the README(before contents)

Accomplished by your PR. Thanks again!

> - Periodically check for unmaintained items and remove them

This sounds good, but I'm not sure where this would go in the current guidelines. Can you suggest somewhere, or open a PR?

> - Add pub link for items that are on pub, the format should be [guthub](github-url)[pub](pub-url) - Description.

There doesn't seem to much value-add from a mandatory pub link. In most cases the GitHub link is more informative and contains a link to Pub. When this isn't the case, a Pub link can be used instead, but I don't think there's any need to require both.
