### ISSUE TITLE
I don't know what thinks the author of this resource about the Dart plugin for Eclipse but I think that this plugin is dead

### ISSUE THREAD

**Issue by mezoni** [yissachar/awesome-dart#36]
[Dart Plugin for Eclipse](https://marketplace.eclipse.org/content/dart-plugin-eclipse)
Date Updated: April 21, 2015 - 10:59

**Comment by yissachar** [comment]
Looks like it's also been removed from the Dartlang site [tools page](https://www.dartlang.org/tools/), so I guess that's another hint that it's well and truly dead. I'll remove it from the list.

Thanks for the heads up :+1:
