### ISSUE TITLE
Change the Angular references

### ISSUE THREAD

**Issue by Stargator** [yissachar/awesome-dart#43]
Under Client Web App Frameworks, there is no difference between Angular and Angular 2.

AngularDart is the newest name and, in AngularDart 4.0, it's pub package will go by the name angular.

Please update.

**Comment by yissachar** [comment]
I'm no longer actively working with Dart. If you can submit a PR with the proposed changes, it will save me the time of trying to research this myself. Thanks!

**Comment by Stargator** [comment]
Will do!
