### ISSUE TITLE
Polymer Dart is unsupported. The Polymer Dart packages are likely to break with Dart 2. For new apps, we recommend that you use AngularDart.

### ISSUE THREAD

**Issue by mezoni** [yissachar/awesome-dart#52]
Polymer Dart is unsupported. The Polymer Dart packages are likely to break with Dart 2. For new apps, we recommend that you use AngularDart.
Source: https://webdev.dartlang.org/guides/polymer

Polymer - Use polymer to build structured, encapsulated, client-side web apps with web components.
Source: https://github.com/yissachar/awesome-dart

**Comment by yissachar** [comment]
Thanks! I've removed it from the list. 👍
