### ISSUE TITLE
Remove angel

### ISSUE THREAD

**Issue by Zerocchi** [yissachar/awesome-dart#92]
I guess it's now good to remove angel from the server frameworks list as the project is archived and no longer maintained.

https://github.com/angel-dart/angel

> Angel is no longer being maintained. You can read my reasons for discontinuing the project here: https://www.reddit.com/r/dartlang/comments/h0z413/looks_like_the_angel_webbackend_framework_wont_be/ftpaxmo/

Or maybe you can modify it to include the forked version instead. It's up to you.

>At the moment, there is one fork of Angel that adds null-safety support. If you intend to upgrade existing Angel projects to the more recent versions of Dart, then it's your best bet.
The fork can be found here: https://github.com/dukefirehawk/angel

**Comment by yissachar** [comment]
Removed, thanks
